#!/bin/bash


bootstrap() {
  git_init
  git_config > /dev/null 2>&1

  install_all > /dev/null 2>&1
  create_link

  download_makefile

  check
}

git_config() {
  git config --global user.email "htilcs1115@gmail.com"
  git config --global user.name "k-nasa"

  git config --global core.editor 'vim -c "set fenc=utf-8"'
}

install_all() {
  install_alp
  install_pt_query_digest
  install_discordcat
}


install_alp() {
  echo 'Install alp'
  wget https://github.com/tkuchiki/alp/releases/download/v1.0.3/alp_linux_amd64.zip
  unzip alp_linux_amd64.zip
  sudo mv alp /usr/local/bin/alp
}

install_pt_query_digest() {
  echo 'Install pt-query-digest'
  wget https://github.com/percona/percona-toolkit/archive/3.0.5-test.tar.gz
  tar zxvf 3.0.5-test.tar.gz
  sudo mv ./percona-toolkit-3.0.5-test/bin/pt-query-digest /usr/local/bin/pt-query-digest
}

install_discordcat() {
  wget https://github.com/k-nasa/discordcat/releases/download/0.1.0/discordcat_x86_64-unknown-linux-gnu.tar.gz
  tar -xf discordcat_x86_64-unknown-linux-gnu.tar.gz
  sudo mv ./discordcat_x86_64-unknown-linux-gnu/discordcat /usr/local/bin/
  sudo chmod +x /usr/local/bin/discordcat
}

create_link() {
  sudo cp /etc/nginx/nginx.conf $HOME/etc && sudo ln -sf $HOME/etc/nginx.conf /etc/nginx/
  sudo cp /etc/mysql/my.cnf $HOME/etc/ && sudo ln -sf $HOME/etc/my.cnf /etc/mysql/
}

git_init() {
  git init
  ssh-keygen && cat $HOME/.ssh/id_rsa.pub

  printf "\e[34mCopy this SSH key (https://github.com/settings/ssh/new)\e[m\n"
  while :
  do
    read -p "Added SSH key? (y/n)" input
    if [ "$input" = "y" ]; then
      echo "Continue to setup!"
      break
    elif [ "$input" = "n" ]; then
      echo "Please Add SSH Key."
    fi
  done

  ssh -T git@github.com
}

checking() {
  which $1 > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    printf "\e[32m [ok]   $1 \e[m\n"
  else
    printf "\e[31m [err]  $1 \e[m \n"
  fi
}

check() {
  printf "\e[33m
  ==============================
  install checking!
  ==============================\n
  \e[m"


  COMMANDS=(alp pt-query-digest htop discordcat)

  for c in ${COMMANDS[@]}; do
    checking $c
  done
}

download_makefile() {
  crul -O https://raw.githubusercontent.com/k-nasa/magic-powder/master/Makefile
}

bootstrap
