name: Test make setup

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run bootstrap
      run: make setup
